#!/bin/bash
#
# Extract CDK outputs to generate .env file for the E2E tests
#
#

set -e


ENV="dev"
DEVELOPER_ID=""
USE_PERSONAL=false


while [[ $# -gt 0 ]]; do
    case $1 in
        --env)
         ENV="$2"
         shift 2
         ;;
        --developer)
         DEVELOPER_ID="$2"
         shift 2
         ;;
        --personal)
         USE_PERSONAL=true
         shift
         ;;
    esac
done

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
E2E_DIR="$(dirname "$SCRIPT_DIR")"
CDK_DIR="$(dirname "$E2E_DIR")/cdk"
ENV_FILE="$E2E_DIR/.env"

rm -f "$ENV_FILE"


if [ "$USE_PERSONAL" = true ] && [ -z "$DEVELOPER_ID" ]; then
    if [ -f "$CDK_DIR/scripts/set-developer.sh" ]; then
        DEVELOPER_ID=$("$CDK_DIR/scripts/set-developer.sh")
        echo "Auto detected developer ID: $DEVELOPER_ID"
    else
        echo "Error: cannot find set-developer script in $CDK_DIR"
        exit 1
    fi
fi

if [ -n "$DEVELOPER_ID" ]; then
    STACK_NAME="${DEVELOPER_ID}-${ENV}-main"
else
    STACK_NAME="${ENV}-main"
fi


get_cfn_output() {
    local stack_name="$1"
    local output_key="$2"

    aws cloudformation describe-stacks --stack-name "$STACK_NAME" \
       --query "Stacks[0].Outputs[?OutputKey=='$output_key'].OutputValue" \
       --output text 2>/dev/null || echo ""
}

if ! aws cloudformation describe-stacks --stack-name "$STACK_NAME" &>/dev/null; then
    echo "Error: Stack '$STACK_NAME' not found"
    echo ""
    echo "Available stacks;"
    aws cloudformation list-stacks \
        --stack-status-filter CREATE_COMPLETE \
        --query "StackSummaries[?contains(StackName, 'main')].StackName" \
        --output table
    exit 1
fi


echo " Getting vars"

API_ENDPOINT=$(get_cfn_output "$STACK_NAME" "ApiEndpoint")
API_ID=$(get_cfn_output "$STACK_NAME" "ApiId")
DYNAMODB_TABLE=$(get_cfn_output "$STACK_NAME" "TableName")
AWS_REGION=$(get_cfn_output "$STACK_NAME" "AwsRegion")


cat > "$ENV_FILE" << EOF
# Auto-generated by extract-cdk-outputs.sh

# API Configuration
API_BASE_URL=$API_ENDPOINT
API_ID=$API_ID


DYNAMODB_TABLE_NAME=$DYNAMODB_TABLE
AWS_REGION=$AWS_REGION
EOF

echo "Done! Env vars created at ${ENV_FILE}"
echo ""
