#!/bin/bash
#
# Extract terraform outputs to generate .env.file for the E2E tests
#
#

set -e

ENV="${1:-dev}"
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
E2E_DIR="$(dirname "$SCRIPT_DIR")"
MODULE_DIR="$(dirname "$E2E_DIR")/modules"
ENV_FILE="$E2E_DIR/.env"


echo "Extracting Terraform outputs for: $DEV"
echo "Module Directory $MODULE_DIR"
echo "ENV FIle $ENV_FILE"

# function to get the terraform outputs
get_tf_output() {
    local module_dir="$1"
    local output_name="$2"
    local is_sensitive="${3:-false}"

    cd "$MODULE_DIR/$module_dir"

    if [ "$is_sensitive" = "true" ]; then
        terraform output -raw "$output_name" 2>/dev/null || echo ""
    else
        terraform output -raw  "$output_name" 2>/dev/null || echo ""
    fi
}

#function to get map value from. terraform outputs
get_tf_map_value() {
    local module_dir="$1"
    local output_name="$2"
    local key="$3"
    local is_sensitive="${4:-false}"

    cd "$MODULE_DIR/$module_dir"

    if [ "$is_sensitive" = "true" ]; then
        terraform output -json "$output_name" 2>/dev/null | jq -r ".[\"$key\"]" || echo ""
    else
        terraform output -json "$output_name" 2>/dev/null | jq -r ".[\"$key\"]" || echo ""
    fi
}

echo "Extracting Api Gateway outputs ..."
API_ENDPOINT=$(get_tf_output "api-gateway" "api_endpoint")
echo " API_BASE_URL: $API_ENDPOINT"

echo "Extracting cognito outputs..."
COGNITO_DOMAIN=$(get_tf_output "cognito" "user_pool_domain")
TOKEN_ENDPOINT=$(get_tf_output "cognito" "token_endpoint")
AWS_REGION="eu-west-2"
FULL_COGNITO_DOMAIN="${COGNITO_DOMAIN}.auth.${AWS_REGION}.amazoncognito.com"
echo " COGNITO_DOMAIN: $FULL_COGNITO_DOMAIN"

M2M_CLIENT_ID=$(get_tf_map_value "cognito" "m2m_client_ids" "flex")
M2M_CLIENT_SECRET=$(get_tf_map_value "cognito" "m2m_client_secrets" "flex" "true")
echo " COGNITO_CLIENT_ID $M2M_CLIENT_ID"
echo " COGNITO_CLIENT_SECRET [redacted]"

echo "Extract dynamo"
DYNAMO_TABLE=$(get_tf_output "dynamodb" "table_name")
echo " DYNAMo_TABLE $DYNAMO_TABLE"


cat > "$ENV_FILE" << EOF
# Auto-generated by extract-tf-outputs.sh

# API Configuration
API_BASE_URL=$API_ENDPOINT

# Cognito M2M Authentication
COGNITO_DOMAIN=$FULL_COGNITO_DOMAIN
COGNITO_CLIENT_FLEX_ID=$M2M_CLIENT_ID
COGNITO_CLIENT_FLEX_SECRET=$M2M_CLIENT_SECRET
COGNITO_CLIENT_FLEX_SCOPES=udp/read udp/write

# DynamoDb (for cleanup)
DYNAMODB_TABLE_NAME=$DYNAMO_TABLE
AWS_REGION=$AWS_REGION

# Cleanup Config
CLEANUP_ENABLED=true
CLEANUP_DRY_RUN=false
EOF

echo "Done! Env vars created at ${ENV_FILE}"
echo ""
