#!/bin/bash
#
# Extract CDK outputs to generate .env file for the E2E tests
#
#

set -e


ENV="dev"
DEVELOPER_ID=""
USE_PERSONAL=false


while [[ $# -gt 0 ]]; do
    case $1 in
        --env)
         ENV="$2"
         shift 2
         ;;
        --developer)
         DEVELOPER_ID="$2"
         shift 2
         ;;
        --personal)
         USE_PERSONAL=true
         shift
         ;;
    esac
done

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
E2E_DIR="$(dirname "$SCRIPT_DIR")"
CDK_DIR="$(dirname "$E2E_DIR")/cdk"
ENV_FILE="$E2E_DIR/.env"

rm -f "$ENV_FILE"


if [ "$USE_PERSONAL" = true ] && [ -z "$DEVELOPER_ID" ]; then
    if [ -f "$CDK_DIR/scripts/set-developer.sh" ]; then
        DEVELOPER_ID=$("$CDK_DIR/scripts/set-developer.sh")
        echo "Auto detected developer ID: $DEVELOPER_ID"
    else
        echo "Error: cannot find set-developer script in $CDK_DIR"
        exit 1
    fi
fi

if [ -n "$DEVELOPER_ID" ]; then
    STACK_NAME="${DEVELOPER_ID}-${ENV}-main"
else
    STACK_NAME="${ENV}-main"
fi


get_cfn_output() {
    local stack_name="$1"
    local output_key="$2"

    aws cloudformation describe-stacks --stack-name "$STACK_NAME" \
       --query "Stacks[0].Outputs[?OutputKey=='$output_key'].OutputValue" \
       --output text 2>/dev/null || echo ""
}


get_cfn_outputs_by_prefix() {
    local stack_name="$1"
    local prefix="$2"

    aws cloudformation describe-stacks \
       --stack-name "$stack_name" \
       --query "Stacks[0].Outputs[?starts_with(OutputKey, '$prefix')].[OutputKey,OutputValue]" \
       --output text 2>/dev/null || echo ""
}

if ! aws cloudformation describe-stacks --stack-name "$STACK_NAME" &>/dev/null; then
    echo "Error: Stack '$STACK_NAME' not found"
    echo ""
    echo "Available stacks;"
    aws cloudformation list-stacks \
        --stack-status-filter CREATE_COMPLETE \
        --query "StackSummaries[?contains(StackName, 'main')].StackName" \
        --output table
    exit 1
fi


echo " Getting vars"

API_ENDPOINT=$(get_cfn_output "$STACK_NAME" "ApiEndpoint")
COGNITO_DOMAIN=$(get_cfn_output "$STACK_NAME" "CognitoDomain")
USER_POOL_ID=$(get_cfn_output "$STACK_NAME" "UserPoolId")
TOKEN_ENDPOINT=$(get_cfn_output "$STACK_NAME" "TokenEndpoint")
DYNAMODB_TABLE=$(get_cfn_output "$STACK_NAME" "TableName")
AWS_REGION=$(get_cfn_output "$STACK_NAME" "AwsRegion")
M2M_OUTPUTS=$(get_cfn_outputs_by_prefix "$STACK_NAME" "M2MClientId")

echo "$M2M_OUTPUTS"

COGNITO_CLIENTS=""
if [ -n "$M2M_OUTPUTS" ]; then
    while IFS=$'\t' read -r output_key client_id; do
        if [ -z "$output_key" ]; then
            continue
        fi

        client_name=$(echo "$output_key" | sed -E 's/^M2MClientId-?//1')

        echo "$client_name $output_key"


        CLIENT_SECRET=$(aws cognito-idp describe-user-pool-client \
            --user-pool-id "$USER_POOL_ID" \
            --client-id "$client_id" \
            --query "UserPoolClient.ClientSecret" \
            --output text 2>/dev/null || echo "")

        ENV_NAME=$(echo "$client_name" | tr '[:lower:]-' '[:upper:]_')

        echo " Found clients $client_name"

        COGNTIO_CLIENTS="${COGNTIO_CLIENTS}
# ${client_name} client
COGNITO_CLIENT_${ENV_NAME}_ID=$client_id
COGNITO_CLIENT_${ENV_NAME}_SECRET=$CLIENT_SECRET
COGNITO_CLIENT_${ENV_NAME}_SCOPES=udp/read udp/write udp/delete"
    done <<< "$M2M_OUTPUTS"
fi


cat > "$ENV_FILE" << EOF
# Auto-generated by extract-cdk-outputs.sh

# API Configuration
API_BASE_URL=$API_ENDPOINT

COGNITO_DOMAIN=$COGNITO_DOMAIN
USER_POOL_ID=$USER_POOL_ID
TOKEN_ENDPOINT=$TOKEN_ENDPOINT
$COGNTIO_CLIENTS


DYNAMODB_TABLE_NAME=$DYNAMODB_TABLE
AWS_REGION=$AWS_REGION
EOF

echo "Done! Env vars created at ${ENV_FILE}"
echo ""
