version: 2
updates:
  - package-ecosystem: npm
    directories:
      - /
      - /e2e
      - /performance
      - /src/*
      - /libs/*
      - /cdk/*      
    schedule:
      interval: weekly
    versioning-strategy: increase
    allow:
      - dependency-type: direct
    groups:
      production-deps:
        dependency-type: production
      dev-deps:
        dependency-type: development

