version: 2
updates:
  - package-ecosystem: npm
    directories:
      - /
    schedule:
      interval: weekly
    cooldown:
      default-days: 7
      semver-major-days: 14
      semver-minor-days: 7
      semver-patch-days: 3
    versioning-strategy: increase-if-necessary
    allow:
      - dependency-type: direct
    groups:
      aws-sdk:
        patterns:
          - '@aws-sdk/*'
          - '@aws-lambda-powertools/*'
          - '@aws-crypto/*'
          - '@smithy/*'
          - 'aws-sdk-client-mock*'
      aws-cdk:
        patterns:
          - aws-cdk
          - aws-cdk-lib
          - cdk-nag
          - constructs
      nx:
        patterns:
          - nx
          - '@nx/*'
      production:
        dependency-type: production
      development:
        dependency-type: development
