FROM public.ecr.aws/docker/library/node:20-slim

RUN corepack enable && corpack prepare pnpm@9 --activate

WORKDIR /workspace

COPY package.json package-lock.json ./
COPY e2e/package.json ./e2e/


RUN npm ci