sonar.organization=govuk-once
sonar.projectKey=govuk-once_user-data-platform

# relative paths to source directories. More details and properties are described
# at https://docs.sonarsource.com/sonarqube-cloud/advanced-setup/analysis-scope/
sonar.sources=src, libs, cdk

# treat the folder tests as test
sonar.tests=e2e

# exclude CDK infrastructure code from coverage
sonar.coverage.exclusions=cdk/**

# enforce quality gates (remove #)
# sonar.qualitygate.wait=true

sonar.javascript.lcov.reportPaths=coverage/*/lcov.info
