version: 0.2

env:
  exported-variables:
    - AWS_ACCESS_KEY_ID
    - AWS_SECRET_ACCESS_KEY
    - AWS_SESSION_TOKEN

phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - curl -sL https://github.com/grafana/k6/releases/download/v0.55.0/K6-v0.55.0-linux-amd64.tar.gz | tar xz
      - mv k6-v0.55.0-linux-amd64/k6 /usr/local/bin
      - k6 version

  pre_build:
    commands:
      - echo "Settin up performance tests"
      - eval $(node performance/scripts/resolve-credentials.mjs)
      - echo "AWS crednetials resolved"


  build:
    commands:
      - echo "Run Performance tests"
      - NX_DAEMON=false NX_PLUGIN_NO_TIMEOUTS=true ./node_modules/.bin/nx run @test/performance:${PERF_TARGET:-smoke} --verbose
      - echo "Perf tests started"
