#!/bin/bash
#
# Set Developer hash for developmnet isolated environments


set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
INFRA_DIR="$(dirname "$SCRIPT_DIR")"

get_developer_id() {
    local git_email
    local git_name
    local hash
    local first_name

    git_email=$(git config --get user.email 2>/dev/null || echo "")
    if [ -z "$git_email" ]; then
        echo "Error: Git email not configured"
        exit 1
    fi

    git_name=$(git config --get user.name 2>/dev/null || echo "")
    if [ -z "$git_name" ]; then
       first_name=$(echo "$git_name" | awk '{print tolower($1)}' | tr -cd 'a-z0-9')
    else
       first_name=$(echo "$git_email" | cut -d'@' -f1 | tr -cd 'a-z0-9' | cut -c1-10)
    fi

    if command -v mdsum &> /dev/null; then
        hash=$(echo -n "$git_email" | md5sum | cut -c1-6)
    elif command -v md5 &> /dev/null; then
        hash=$(echo -n "$git_email" | md5 | cut -c1-6)
    else
         hash=$(echo -n "$git_email" | shasum -a 256 | cut -c1-6)
    fi

    echo "${first_name}-${hash}"
}

generate_backend_config() {
    local module_dir="$1"
    local module_name="$2"
    local developer="$3"
    local env="${4:-dev}"

    local source_file="${INFRA_DIR}/backend.tfvars"
    local target_file="$module_dir/backend.tfvars"

    if [ ! -f "$source_file" ]; then
        echo "Warning $source_file not found"
        return
    fi

    echo "$source_file"

    local bucket=$(awk -F'"' '/^bucket/ {print $2}' "$source_file")

    cat > "$target_file" << EOF
# Auto-generated by set-developer.sh
# Developer: $developer

bucket          = "$bucket"
key             = "$developer/$env/$module_name/terraform.tfstate"
region          = "eu-west-2"
use_lockfile    = true
EOF

}

generate_all_backends() {
    local developer="$1"
    local env="${2:-dev}"

    echo "Generating backend config $INFRA_DIR"

    for module_dir in "$INFRA_DIR"/modules/*/; do
        local module_name=$(basename "$module_dir")


        [[ "$module_name" == "lambda-base" ]] && continue

        generate_backend_config "$module_dir" "$module_name" "$developer" "$env"

        cat > "$module_dir/terraform.auto.tfvars" << EOF
#Auto Generated by set-developer.sh
developer = "$developer"
EOF
        echo " Generated modules/$module_name/{backend.terraform}.auto.tfvars"

    done

}

DEVELOPER_ID=$(get_developer_id)



case "${1:-1}": in
    --value)
        echo "$DEVELOPER_ID"
        ;;
    --export)
        echo "export Developer=$DEVELOPER_ID"
        ;;
    *)

    generate_all_backends "$DEVELOPER_ID" "${2:-dev}"
    ;;
esac
