name: Performance Tests

on:
  workflow_call:
    inputs:
      environment:
        description: 'Target Environment'
        required: true
        type: string
      stack-prefix:
        description: 'CFN stack prefix (eg dev, pr-123)'
        required: true
        type: string
      perf-target:
        description: 'Performacne target for test run'
        required: false
        type: string
        default: 'smoke'
    secrets:
      DEVELOPMENT_ROLE:
        required: true

permissions:
  id-token: write
  contents: read

jobs:
  perf-test:
    name: Performance tests (${{ inputs.environment }})
    runs-on: ubuntu-latest
    continue-on-error: true

    steps:
      - name: Configure Aws Credentials
        uses: aws-actions/configure-aws-credentials@56d6a583f00f6bad6d19d91d53a7bc3b8143d0e9 # v5.1.1
        with:
          role-to-assume: ${{ secrets.DEPLOYMENT_ROLE }}
          aws-region: ${{ inputs.aws-region }}

      - name: Get Perf Codebuild project name
        id: get-perf-project
        env:
          STACK_NAME: ${{ inputs.stack-prefix }}-perf
        run: |
          PERF_PROJECT=$(aws cloudformation describe-stacks --stack-name "${STACK_NAME}" --query "Stacks[0].Outputs[?OutputKey=='PerfCodeBuildProjectName'].OutputValue" --output text)
          echo "perf-project=${PERF_PROJECT}" >> $GITHUB_OUTPUT
          echo "Perf Codebuild Project: ${PERF_PROJECT}"

      - name: Start Performance tests (fire-and-forget)
        env:
          PERF_PROJECT: ${{ steps.get-perf-project.outputs.perf-project }}
          PERF_TARGET: ${{ inputs.perf-target }}
        run: |
          echo "Starting performance tests: ${PERF_PROJECT}"
          BUILD_ID=$(aws codebuild start-build \
            --project-name "${PERF_PROJECT}" \
            --environment-variables-override "name=PERF_TARGET,value={PERF_TARGET},type=PLAINTEXT" \
            --query 'build.id' --output text)
          echo "Performance test build started ${BUILD_ID}"
          echo "Build will run independently - failures will be notified in slack channel"
