on:
  workflow_call:

jobs:
  validate-pr-title:
    name: Validate PR Title
    runs-on: ubuntu-latest

    steps:
      - name: Skip Dependabot PRs
        if: github.actor == 'dependabot[bot]'
        run: echo "Skipping Jira title check for Dependabot"

      - name: Validate PR title contains Jira ticket
        if: github.actor != 'dependabot[bot]'
        env:
          TITLE: ${{ github.event.pull_request.title }}
        run: |
          echo "Checking PR title: $TITLE"
          if [[ ! $TITLE =~ ^[A-Z]{3,4}-[1-9][0-9]{0,4}:\ .+ ]]; then
            echo "::error ::PR title must follow the format 'UDP-123: Description'"
            exit 1
          fi
