name: Slack Release Notification

on:
  workflow_call:
    inputs:
      version:
        required: true
        type: string
      type:
        required: true
        type: string
    secrets:
      DEPLOYMENT_ROLE:
        required: true
      RELEASE_NOTIFICATIONS_TOPIC_ARN:
        required: true

permissions:
  id-token: write
  contents: read

jobs:
  send-notification:
    name: Send Release Notification
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout code
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Setup pnpm
        uses: pnpm/action-setup@0977fd99725f1db4007ccb2928dbb4e90d06cc86 # v6.0.10

      - name: Setup node
        uses: actions/setup-node@395ad3262231945c25e8478fd5baf05154b1d79f #v6
        with:
          node-version: 24
          cache: pnpm

      - name: Install dependencies
        run: pnpm i --frozen-lockfile

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@56d6a583f00f6bad6d19d91d53a7bc3b8143d0e9 # v5.1.1
        with:
          role-to-assume: ${{ secrets.DEPLOYMENT_ROLE }}
          aws-region: eu-west-2
          role-session-name: ${{ github.run_id }}

      - name: Publish to SNS
        continue-on-error: true
        env:
          GH_TOKEN: ${{ github.token }}
          VERSION: ${{ inputs.version }}
          TYPE: ${{ inputs.type }}
          TITLE: 'UDP ${{ inputs.type }} release: v${{ inputs.version }}'
          URL: 'https://github.com/${{ github.repository }}/releases/tag/v${{ inputs.version }}'
          TOPIC_ARN: ${{ secrets.RELEASE_NOTIFICATIONS_TOPIC_ARN }}
        run: |
          MESSAGE=$(gh release view "v${VERSION}" \
          --repo "${{ github.repository }}" \
          --json body \
          --jq .body \
          | pnpm exec tsx scripts/build-release-notification.ts)

          aws sns publish --topic-arn "$TOPIC_ARN" --message "$MESSAGE"
