name: Spike Test (Manual)

on:
  workflow_dispatch:

jobs:
  spike-test:
    uses: ./.github/workflows/__perf-test.yml
    with:
      environment: stag
      stack-prefix: stag
      aws-region: eu-west-2
      perf-target: read-heavy-spike
    secrets:
      DEPLOYMENT_ROLE: ${{ secrets.STAGING_DEPLOYMENT_ROLE }}
