name: Create Release

on:
  workflow_call:
    outputs:
      version:
        description: 'The new semantic version number'
        value: ${{ jobs.version.outputs.version }}
      type:
        description: 'The type of release (major, minor, patch)'
        value: ${{ jobs.version.outputs.type }}

env:
  NODE_VERSION: '22'

permissions:
  contents: write
  issues: write
  pull-requests: write

jobs:
  version:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.release.outputs.version }}
      type: ${{ steps.release.outputs.type }}
    steps:
      - name: Checkout code
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 #v6
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Generate GitHub App Token
        id: generate-token
        uses: actions/create-github-app-token@v2
        with:
          app-id: ${{ secrets.GH_UDPTAGRELEASE_GOVUK_ONCE_APP_ID }}
          private-key: ${{ secrets.GH_UDPTAGRELEASE_GOVUK_ONCE_PRIVATE_KEY }}

      - name: Setup pnpm
        uses: pnpm/action-setup@v6
        with:
          version: 9

      - name: Setup node
        uses: actions/setup-node@v6
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm i --frozen-lockfile

      - name: Run semantic release
        id: release
        run: pnpm run semantic:release
        env:
          GITHUB_TOKEN: ${{ steps.generate-token.outputs.token }}

      - name: Release Outputs
        run: |
          echo "The next version is ${{ steps.release.outputs.version }}"
          echo "The release type is ${{ steps.release.outputs.type }}"
          echo "The release notes are generated"
